export const ENGLISH_TERMS = [
'People to be included',
'Include',
'Max levels',
'Relation',
'Siblings',
'All relatives',
'Partners',
'Anyone',
'XREFs of included individuals',
'Stop processing on',
'Non-relatives',
'Mark not blood-related people with different colour',
'Ignore unseen links to speed up relative check',
'Treatment of source individuals',
'Default',
'Add to list',
"Don't add to list",
'Overwrite',
'Clear all',
'Toggle advanced settings',

'Appearance',
'Graph direction',
'Left-to-right',
'Top-to-bottom',
'Diagram type',
'Separated',
'Combined',
'Tile design',
'Shapes',
'Individual tile shape',
'Rectangle',
'Rounded rectangle',
"Based on individual's sex",
'Based on vital status',
'Male',
'Female',
'Other',
'Unknown',

'Photos',
'Show photos of individuals',
'Show first birth image',
'Show first marriage image',
'Show first divorce image',
'Show first death image',
'Show first burial image',
'Photo shape',
'No change',
'Oval',
'Circle',
'Square',
'Rounded square',
'Photo size',
'Photo resolution',

'Colours',
'Individual background colour',
'Custom',
'Based on age',
'Custom background colour',
'Deceased',
'Living',
'Low age colour',
'High age colour',
'Unknown age colour',
'Age for low colour',
'Age for high colour',
'No stripe',
'Individual border colour',
'Same as family border',
'Style individuals based on shared note',
'Default background colour for new items:',
'Add shared note style:',
'No styles set based on shared notes.',
'Edit shared notes',

'Male individuals',
'Female individuals',
'Other gender individuals',
'Unknown gender individuals',
'Not blood-related male individuals',
'Not blood-related female individuals',
'Not blood-related other gender individuals',
'Not blood-related unknown gender individuals',

'Show selected individuals in different colour',
'Default highlight colour',
'Show selected families in different colour',

'Family background',
'Family border colour',

'Font',
'Typeface',
'Font size for names',
'Font size for details',
'Font colour for names',
'Font colour for details',

'Page links',
'Tile contents',
'Add URL to individuals and families',
'(browser, SVG, and PDF only)',

'Abbreviations',
'Abbreviated names',
'Full name',
'Given and surnames',
'Given names',
'First given name only',
'Preferred given name and surname',
'Surnames',
'Initials only',
'Given name initials and surname',
"Don't show names",

'Abbreviated place names',
'Full place name',
'City and country',
'City and 2 letter ISO country code',
'City and 3 letter ISO country code',

'Abbreviated month names',
'Show individual XREF',
'Show birthdate',
'Year',
'Full date',
'Show birth place',
'Show death date',
'Show death place',
'Show burial date',
'Show burial place',
'Show sex of individuals',
'Use similar events if information not available',
'Show family XREF',
'Show marriages',
'Show only first marriage',
'Show marriage date',
'Show marriage place',
'Show marriage type',
'Show divorces',
'Show only first divorce',
'Show divorce place',

'Approximate size of diagram as PDF',
'Diagram',
'Diagram DPI',
'Spacing',
'Between generations',
'Between individuals on the same level',
'Layout',
'Partner position',
'(Combined diagram type only)',
'Side by side',
'Stacked',
'Diagram style',
'Arrow style',
'Solid',
'Dotted',
'Dashed',
'Bold',
'Tapered',
'Random',
'None',
'Arrow colour',
'Relationship arrow colour',
'Show blood relationship in different colour',
'Related by birth',
'Related other than by birth',
'Add arrow label when pedigree type is not "birth"',
'Diagram background colour',

'General settings',
'Output file type',
'Quality of JPG photos',
'Lowest',
'Low',
'Medium',
'High',
'Highest',
'Convert photos to JPG where possible',
'Browser render',
'Auto-update',

"Action when individual clicked",
"Open individual's page",
'Add individual to list of starting individuals',
'Replace starting individuals with this individual',
'Add this individual to the list of stopping individuals',
'Replace stopping individuals with this individual',
'Add to list of individuals to highlight',
'Add a partner',
'Add a parent',
'Show menu',
'Do nothing',

'Action when family clicked',
'Open family page',
'Add a child',
'Add to list of families to highlight',
'Change family members',

'Save settings',
'Save',
'Settings list sort order',
'Oldest first',
'Newest first',
'Alphabetical order',
'Reverse alphabetical order',
'Show saved diagrams panel',
'Only save settings that affect diagram',

'Settings file',
'Load settings from file',

'Message history',
'View message history',

'Update',
'Download',
'Reset',
'Help',
];