<?php

use vendor\WebtreesModules\gvexport\GVExport;
use vendor\WebtreesModules\gvexport\MainPage;
use Fisharebest\Webtrees\I18N;
use vendor\WebtreesModules\gvexport\Settings;

/**
 * @var GVExport    $module         this module
 * @var array       $vars           array of saved settings
 * @var array       $settings       full settings data including dropdown options
 * @var bool        $admin          whether this is for the admin page (remove functions that aren't settings)
 */

?>

<?= MainPage::addLabel('', 'Diagram', !$admin); ?>
<div class="col-sm-8 options-panel-background">
    <div onclick="Form.showHideSubgroup('dpi_subgroup', this)" class="pointer subgroup">→ <?= I18N::translate('Diagram DPI'); ?></div>
    <div id="dpi_subgroup" class="setting_subgroup col-auto options-panel-background" style="display: none">
        <div class="row">
            <label for="dpi"><?= I18N::translate('DPI') ?></label>
            <div class="col-auto">
                <input type="text" onblur="Form.setDefaultValueIfBlank(this, 72)" class="form-control col-sm-6" size="5" name="vars[dpi]" id="dpi"
                       value="<?= I18N::digits($vars['dpi']); ?>">
            </div>
        </div>
    </div>

    <div onclick="Form.showHideSubgroup('spacing_subgroup', this)" class="pointer subgroup">→ <?= I18N::translate('Spacing'); ?></div>
    <div id="spacing_subgroup" class="setting_subgroup col-auto options-panel-background" style="display: none">
        <div class="row">
            <label for="ranksep"><?= I18N::translate('Between generations') ?></label>
            <div class="col-auto">
                <input type="text" onclick="Form.togglePercent(this, false)" onblur="Form.togglePercent(this, true)" class="form-control col-sm-6" size="5" name="vars[ranksep]" id="ranksep"
                       value="<?= e($vars["ranksep"]) ?>">
            </div>
            <label for="nodesep"><?= I18N::translate('Between individuals on the same level') ?></label>
            <div class="col-auto">
                <input type="text" onclick="Form.togglePercent(this, false)" onblur="Form.togglePercent(this, true)" class="form-control col-sm-6" size="5" name="vars[nodesep]" id="nodesep"
                       value="<?= e($vars["nodesep"]) ?>">
            </div>
        </div>
    </div>

    <div onclick="Form.showHideSubgroup('diagtype_combined_subgroup', this)" class="pointer subgroup">→ <?= I18N::translate('Layout'); ?></div>
    <div id="diagtype_combined_subgroup" class="setting_subgroup col-auto options-panel-background" style="display: none">
        <div class="row">
            <div><?= I18N::translate('Partner position') ?>:</div>
            <div class="font-small">(<?= I18N::translate('Combined diagram type only') ?>)</div>
            <div>
                <div class="padding-left-10">
                    <input type="radio" name="vars[combined_layout_type]" id="cl_type_ss" value="SS" <?= $vars["combined_layout_type"] == 'SS' ? 'checked' : '' ?>>
                    <label for="cl_type_ss"><?= I18N::translate('Side by side') ?></label>
                </div>
                <div class="padding-left-10">
                    <input type="radio" name="vars[combined_layout_type]" id="cl_type_ou" value="OU" <?= $vars["combined_layout_type"] == 'OU' ? 'checked' : '' ?>>
                    <label for="cl_type_ou"><?= I18N::translate('Stacked') ?></label>
                </div>
            </div>
        </div>
    </div>

    <div onclick="Form.showHideSubgroup('diagram_colours_subgroup', this)" class="pointer subgroup">→ <?= I18N::translate('Diagram style'); ?></div>
    <div id="diagram_colours_subgroup" class="setting_subgroup col-auto options-panel-background" style="display: none">
        <div class="row">
            <div class="col-sm-12 col-auto">
                <label for="arrow_style"><?= I18N::translate('Arrow style'); ?></label>
                <?= view('components/select', ['name' => 'vars[arrow_style]', 'id' => 'arrow_style', 'selected' => I18N::digits($vars['arrow_style']), 'options' => MainPage::updateTranslations($settings["arrow_style_options"])]) ?>
            </div>
            <div class="col-sm-12 col-auto">
                <label for="arrow_colour_type"><?= I18N::translate('Arrow colour'); ?></label>
                <?= view('components/select', ['name' => 'vars[arrow_colour_type]', 'id' => 'arrow_colour_type', 'selected' => I18N::digits($vars['arrow_colour_type']), 'options' => MainPage::updateTranslations($settings["arrow_colour_type_options"])]) ?>
                <?= view($module->name() . '::MainPage/Appearance/TileDesign/Subgroup',['view' => $module->name() . '::MainPage/Appearance/TileDesign/CustomArrowColourSubgroup', 'view_options' => ['module' => $module, 'vars' => $vars, 'admin' => $admin, 'group' => 'arrow_colour_type', 'field' => 'custom', 'select_id' => 'arrow_colour_type', 'option_id' => Settings::OPTION_ARROW_CUSTOM_COLOUR, 'picker_list' => ['arrows_default' => 'Relationship arrow colour']]]); ?>
            </div>
            <div class="col-sm-12 col-auto">
                <input type="color" class="picker" name="vars[background_col]" id="background_col" value="<?= e($vars["background_col"]); ?>" /><label for="background_col" class="picker-label"><?= I18N::translate('Diagram background colour') ?></label>
            </div>
        </div>
    </div>
</div>
