name: Qodana
on:
  workflow_dispatch:
  pull_request:
  push:
    branches: # Specify your branches here
      - main # The 'main' branch

jobs:
  qodana:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
      checks: write
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.sha }}  # to check out the actual pull request commit, not the merge commit
          fetch-depth: 0  # a full history is required for pull request analysis
      - name: 'Qodana Scan'
        uses: JetBrains/qodana-action@v2024.1
        env:
          QODANA_TOKEN: ${{ secrets.QODANA_TOKEN }}
      - name: Run Qodana Docker Container
        run: |
          docker run \
          -p 8080:8080 \
          -v ${{ github.workspace }}:/data/project \
          -v ${{ github.workspace }}/res:/data/results/ \
          jetbrains/qodana-php:latest \
          --show-report \
          --baseline=/data/project/qodana.sarif.json
      
      
              
